# Generated by Django 3.2.6 on 2021-08-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fad',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
